FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN apt-get update && apt-get install -y curl && \
    curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
    apt-get install -y nodejs && \
    rm -rf /var/lib/apt/lists/*

RUN node -v && npm -v

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["reflex", "run", "--env", "prod", "--frontend-port", "3000", "--backend-port", "8001", "--backend-host", "0.0.0.0"]